### ISSUE TITLE
CI failure

### ISSUE THREAD

**Issue by glennj** [exercism/sed#11]
@jimmytty are you keeping your eye on CI failures?

https://github.com/exercism/sed/commit/6a42da1e97874f33bb684bc596a8c3dc2290c903
https://github.com/exercism/sed/actions/runs/9915553748/job/27396578539

**Comment by jimmytty** [comment]
I was ignoring them until now.
I stopped doing new exercises (more coming soon) and now I'm going to take a look at CI integration. (https://exercism.org/docs/building/tracks/new/setup-continuous-integration). It seems like an "easy job" (I hope), so I'll resolve the issue in the next few hours.

**Comment by glennj** [comment]
Fixing the problems listed in my 2nd link would be a good start.

**Comment by jimmytty** [comment]
Sorry @glennj! I misunderstood the problems thinking they were about "[Setup Continuous Integration](https://exercism.org/docs/building/tracks/new/setup-continuous-integration)". I'm trying to follow step-by-step the first opened issue [Launch tracking #1](https://github.com/exercism/sed/issues/1) and the linting problems are one step ahead of "Setup Continuous Integration". I finally started to use `./bin/verify-exercises` (very basic) and `./bin/configlet lint` and already committed the the fixes. Anyway, I'm still looking at the documentation and I'll continue to improve the configuration.

Thank you for your observations.

**Comment by glennj** [comment]
Good old communication... I could have been more clear as you are new to this infrastructure. By "CI" I meant the github workflows configured in https://github.com/exercism/sed/tree/main/.github/workflows

The configlet workflow runs for every commit to main, so filling the missing parts of config.json can be a top priority.

I'll create a issue for it and assign it to myself.

**Comment by glennj** [comment]
Also, speaking of communication, where would you prefer to talk about the sed track? In PRs and issues here, on the exercism forum, on discord?

**Comment by jimmytty** [comment]
> Also, speaking of communication, where would you prefer to talk about the sed track? In PRs and issues here, on the exercism forum, on discord?

I don't know the best way to discuss sed track and I welcome suggestions. I prefer to use the same "workflow" as you all.

For example, IMHO, Github is good for discussing repository issues, while the exercise forum is good for open discussions and ideas and is more formal and restricted than discord. Maybe a mix of them all can be the best approach, but I'm new and it's easy to me to make a mess.

**Comment by glennj** [comment]
I was just checking to see if you have any strong preferences. I agree that github is the place to discuss specifics, and the forum to discuss bigger topics.

**Comment by glennj** [comment]
The original reason for this issue has been resolved.
